### ISSUE TITLE
Is ask question implemented?

### ISSUE THREAD

**Issue by leonardodepaula** [yeazin/Stackoverflow-Clone#24]
Hi! Your project looks very good, but I coudn't get if the ask question model/view is already implemented. Is it?

Thanks.

**Comment by yeazin** [comment]
No, We are working on this matter. 
We will update the code soon. 
after that, if you want to contribute to another section, Feel free to ask Brother

**Comment by leonardodepaula** [comment]
Thank you. I will clone the project when I get some free time.
